### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by idhard** [sonata-project/SonataCommentBundle#23]
Where can i find the documentation about the installation of this module ? the link on the repository is broken.
Thanks!

**Comment by chrisRidgers** [comment]
Is this bundle still current?  I'm seeing German language updates from 9 days ago, yet there's no documentation link, and the sonata website makes no mention of the bundles existence?

**Comment by Soullivaneuh** [comment]
The bundle is not ready yet so no online documentation for the moment.

If you want to use it, please see: https://github.com/sonata-project/SonataCommentBundle/tree/master/Resources/doc/reference

**Comment by chrisRidgers** [comment]
That's good to know thanks, might i recommend sticking that in the Readme so people don't stress looking for stuff like I did :)

**Comment by core23** [comment]
@Soullivaneuh Can you say what's missing for this bundle?

**Comment by OskarStark** [comment]
any news here @Soullivaneuh ?

**Comment by psyray** [comment]
Hi,

Does this bundle usable ?
I've configured it but nothing is showed on desired page (overrided base_show.html.twig).

Ajax call is correct, json return also, but nothing is showed on page.
Datas returned by the AJAX call are
```
{"comments":[],"sorter":"date","thread":{"id":0,"is_commentable":true,"num_comments":0,"permalink":"http:\/\/myurl.com\/index.php\/admin\/app\/myentity\/1\/show"},"view":"tree"}
```

**Comment by psyray** [comment]
Understand my problem, solution was to generate HTML output in FOS REST config
```
fos_rest:
    routing_loader:
        include_format: false
    view:
        view_response_listener: true
    format_listener:
        rules:
            - { path: '^/api/threads', priorities: ['html'], fallback_format: 'html' }
            - { path: '^/api/', priorities: ['json'], fallback_format: 'json' }
```
